# Generated by Django 4.2.29 on 2026-03-18 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('value', models.TextField()),
            ],
            options={
                'db_table': 'feed_setting',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='twitter_user', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('icon_url', models.URLField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('is_important', models.BooleanField(default=False)),
                ('priority', models.CharField(blank=True, max_length=20, null=True)),
                ('follower_count', models.IntegerField(blank=True, null=True)),
                ('custom_multiplier', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'feed_source',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=500, unique=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_starred', models.BooleanField(default=False)),
                ('like_count', models.IntegerField(blank=True, null=True)),
                ('reply_count', models.IntegerField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='feed.source')),
            ],
            options={
                'db_table': 'feed_item',
                'indexes': [models.Index(fields=['source'], name='feed_item_source__a522ad_idx'), models.Index(fields=['-published_at'], name='feed_item_publish_9dde4a_idx'), models.Index(fields=['is_starred'], name='feed_item_is_star_558fdd_idx')],
            },
        ),
    ]
