# Generated by Django 4.2.30 on 2026-10-01 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['-fetched_at'], name='feed_item_fetched_f425b1_idx'),
        ),
    ]
