# Generated by Django 4.2.30 on 2026-10-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_item_feed_item_fetched_f425b1_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='engagement_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='promoted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
